<?php 
$con = $rid['sqlConnect'];
$u = $_SESSION['rid_username'];
$datadefp = $rid['dataUser'];
if ($rid['web_setting']['autoreply_button'] == '1' && $datadefp['send_button'] == '1') { ?>
    <div class="card">
        <div class="card-body">
            <button class="btn btn-info float-right" onclick="rid_AddAutoReply();"><?php echo rid_lang('add_auto_reply');?></button>
            <h6 class="card-title"><?php echo rid_lang('auto_reply');?> list button</h6>
            <div class="row">
                <div class="col-md-12" style="margin-bottom:0;">
                    <div class=" add_category_form_alert"></div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <br>
            <div class="table-responsive">
                <table id="example" class="table key-buttons text-md-nowrap">
                    <thead>
                        <tr>
                           <th>KEYWORD</th>
                           <th>TEXT SMALL</th>
                           <th>FOOTER</th>
                           <th>TITLE MESSAGE</th>
                           <th>BUTTON TEXT</th>
                           <th>TITLE SECTION</th>
                           <th>TITLE LIST 1</th>
                           <th>TITLE LIST KEYWORD 1</th>
                           <th>TITLE LIST DESC 1</th>
                           <th>TITLE LIST 2</th>
                           <th>TITLE LIST KEYWORD 2</th>
                           <th>TITLE LIST DESC 2</th>
                           <th>TITLE LIST 3</th>
                           <th>TITLE LIST KEYWORD 3</th>
                           <th>TITLE LIST DESC 3</th>
                           <th><?php echo rid_lang('number');?></th>
                           <th>USERNAME</th>
                           <th>action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $u = $_SESSION['rid_username'];
                        $q = mysqli_query($con, "SELECT * FROM list_button WHERE username = '$u'");
                        while ($row = mysqli_fetch_assoc($q)) { ?>
                        <tr id="<?= $row['id'];?>" data-selected="<?= $row['id'];?>">
                            <td><?= $row['keyword']; ?></td>
                            <td><?= $row['text_small']; ?></td>
                            <td><?= $row['footer']; ?></td>
                            <td><?= $row['title_message']; ?></td>
                            <td><?= $row['buttontext']; ?></td>
                            <td><?= $row['title_section']; ?></td>
                            <td><?= $row['title_list_1']; ?></td>
                            <td><?= $row['title_list_keyword_1']; ?></td>
                            <td><?= $row['title_list_desc_1']; ?></td>
                            <td><?= $row['title_list_2']; ?></td>
                            <td><?= $row['title_list_keyword_2']; ?></td>
                            <td><?= $row['title_list_desc_2']; ?></td>
                            <td><?= $row['title_list_3']; ?></td>
                            <td><?= $row['title_list_keyword_3']; ?></td>
                            <td><?= $row['title_list_desc_3']; ?></td>
                            <td><?= $row['number'];?></td>
                            <td><?= $row['username'];?></td>
                            <td>
                                <button onclick="rid_edits(`<?= $row["id"];?>`,`<?= $row["keyword"]; ?>`,`<?= $row["text_small"]; ?>`,`<?= $row["footer"]; ?>`,`<?= $row["title_message"]; ?>`,`<?= $row["buttontext"]; ?>`,`<?= $row["title_section"]; ?>`,`<?= $row["title_list_1"]; ?>`,`<?= $row["title_list_keyword_1"]; ?>`,`<?= $row["title_list_desc_1"]; ?>`,`<?= $row["title_list_2"]; ?>`,`<?= $row["title_list_keyword_2"]; ?>`,`<?= $row["title_list_desc_2"]; ?>`,`<?= $row["title_list_3"]; ?>`,`<?= $row["title_list_keyword_3"]; ?>`,`<?= $row["title_list_desc_3"]; ?>`,`<?= $row["number"]; ?>`,`<?= $row["username"]; ?>`);" type="button" class="btn bg-danger admn_table_btn">Edit</button>
                                <button onclick="rid_delete('<?= $row["id"];?>','hide');" type="button" class="btn bg-danger admn_table_btn"><?php echo rid_lang('delete');?></button>
                            </td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

<script>

const sleep = (milliseconds) => {
  return new Promise(resolve => setTimeout(resolve, milliseconds))
}

function rid_edit() {
    $('#edit_autoreply').submit();
}

function rid_add() {
    $('#add_autoreply').submit();
}

$(document).ready(function () {
  $("#edit_autoreply").submit(function (event) {
      const id = document.getElementById("id");
      const keyword = document.getElementById("keyword_edit");
      const text_small = document.getElementById("text_small_edit");
      const footer = document.getElementById("footer_edit");
      const title_message = document.getElementById("title_message_edit");
      const buttontext = document.getElementById("buttontext_edit");
      const title_section = document.getElementById("title_section_edit");
      const title_list_1 = document.getElementById("title_list_1_edit");
      const title_list_keyword_1 = document.getElementById("title_list_keyword_1_edit");
      const title_list_desc_1 = document.getElementById("title_list_desc_1_edit");
      const title_list_2 = document.getElementById("title_list_2_edit");
      const title_list_keyword_2 = document.getElementById("title_list_keyword_2_edit");
      const title_list_desc_2 = document.getElementById("title_list_desc_2_edit");
      const title_list_3 = document.getElementById("title_list_3_edit");
      const title_list_keyword_3 = document.getElementById("title_list_keyword_3_edit");
      const title_list_desc_3 = document.getElementById("title_list_desc_3_edit");
      
      const edit = {
          id: id.value,
          keyword: keyword.value,
          text_small: text_small.value,
          footer: footer.value,
          title_message: title_message.value,
          buttontext: buttontext.value,
          title_section: title_section.value,
          title_list_1: title_list_1.value,
          title_list_keyword_1: title_list_keyword_1.value,
          title_list_desc_1: title_list_desc_1.value,
          title_list_2: title_list_2.value,
          title_list_keyword_2: title_list_keyword_2.value,
          title_list_desc_2: title_list_desc_2.value,
          title_list_3: title_list_3.value,
          title_list_keyword_3: title_list_keyword_3.value,
          title_list_desc_3: title_list_desc_3.value
      };
      
      $.ajax({
          url: rid_request_file() + '?f=edit_listbutton',
          beforeSend: function() {
              $('.langsModalAlert').html('<div class="alert alert-info">Waiting...</div>')
          },
          type: "POST",
          data: edit,
      }).done(async (data) => {
          console.log(data);
          var ridCans = JSON.parse(data);
          if (ridCans.status == 200) {
              await sleep(2000);
              $('#langsModal').modal('hide');
              location.reload();
          } else {
              console.log('this error ' + data);
              $('.langsModalAlert').html('<div class="alert alert-danger">'+ridCans.message+'</div>');
              setTimeout(function () {
                  $('.langsModalAlert').empty();
              }, 5000);
          }
          $("#langsModal").animate({ scrollTop: 0 }, 100);
      });
    event.preventDefault();
  });
});

    
$(document).ready(function () {
  $("#add_autoreply").submit(function (event) {
      const sender = document.getElementById("sender");
      const keyword = document.getElementById("keyword");
      const text_small = document.getElementById("text_small");
      const footer = document.getElementById("footer");
      const title_message = document.getElementById("title_message");
      const buttontext = document.getElementById("buttontext");
      const title_section = document.getElementById("title_section");
      const title_list_1 = document.getElementById("title_list_1");
      const title_list_keyword_1 = document.getElementById("title_list_keyword_1");
      const title_list_desc_1 = document.getElementById("title_list_desc_1");
      const title_list_2 = document.getElementById("title_list_2");
      const title_list_keyword_2 = document.getElementById("title_list_keyword_2");
      const title_list_desc_2 = document.getElementById("title_list_desc_2");
      const title_list_3 = document.getElementById("title_list_3");
      const title_list_keyword_3 = document.getElementById("title_list_keyword_3");
      const title_list_desc_3 = document.getElementById("title_list_desc_3");
      
      const addbutton = {
          sender: sender.value,
          keyword: keyword.value,
          text_small: text_small.value,
          footer: footer.value,
          title_message: title_message.value,
          buttontext: buttontext.value,
          title_section: title_section.value,
          title_list_1: title_list_1.value,
          title_list_keyword_1: title_list_keyword_1.value,
          title_list_desc_1: title_list_desc_1.value,
          title_list_2: title_list_2.value,
          title_list_keyword_2: title_list_keyword_2.value,
          title_list_desc_2: title_list_desc_2.value,
          title_list_3: title_list_3.value,
          title_list_keyword_3: title_list_keyword_3.value,
          title_list_desc_3: title_list_desc_3.value
      };
      
      $.ajax({
          url: rid_request_file() + '?f=add_listbutton',
          beforeSend: function() {
              $('.langsModalAlert').html('<div class="alert alert-info">Waiting...</div>')
          },
          type: "POST",
          data: addbutton,
      }).done(async (data) => {
          console.log(data);
          var ridCans = JSON.parse(data);
          if (ridCans.status == 200) {
              await sleep(2000);
              $('#langsModal').modal('hide');
              location.reload();
          } else {
              console.log('this error ' + data);
              $('.langsModalAlert').html('<div class="alert alert-danger">'+ridCans.message+'</div>');
              setTimeout(function () {
                  $('.langsModalAlert').empty();
              }, 5000);
          }
          $("#langsModal").animate({ scrollTop: 0 }, 100);
      });
    event.preventDefault();
  });
});

function rid_edits(id,keyword,text_small,footer,title_message,buttontext,title_section,title_list_1,title_list_keyword_1,title_list_desc_1,title_list_2,title_list_keyword_2,title_list_desc_2,title_list_3,title_list_keyword_3,title_list_desc_3,number,username) {
    $('#edit_listbuttons').modal('show');
    document.getElementById("id").setAttribute("value", id);
    document.getElementById("keyword_edit").setAttribute("value", keyword);
    document.getElementById("text_small_edit").value = text_small;
    document.getElementById("footer_edit").setAttribute("value", footer);
    document.getElementById("title_message_edit").setAttribute("value", title_message);
    document.getElementById("buttontext_edit").setAttribute("value", buttontext);
    document.getElementById("title_section_edit").setAttribute("value", title_section);
    document.getElementById("title_list_1_edit").setAttribute("value", title_list_1);
    document.getElementById("title_list_keyword_1_edit").setAttribute("value", title_list_keyword_1);
    document.getElementById("title_list_desc_1_edit").setAttribute("value", title_list_desc_1);
    document.getElementById("title_list_2_edit").setAttribute("value", title_list_2);
    document.getElementById("title_list_keyword_2_edit").setAttribute("value", title_list_keyword_2);
    document.getElementById("title_list_desc_2_edit").setAttribute("value", title_list_desc_2);
    document.getElementById("title_list_3_edit").setAttribute("value", title_list_3);
    document.getElementById("title_list_keyword_3_edit").setAttribute("value", title_list_keyword_3);
    document.getElementById("title_list_desc_3_edit").setAttribute("value", title_list_desc_3);
    document.getElementById("number").setAttribute("value", number);
    document.getElementById("username").setAttribute("value", username);
}

function rid_AddAutoReply() {
    $('#add_autoreplyh').modal('show');
}

function rid_delete(key,type = 'show') {
  if (key == '') {
    return false;
  }
  if (type == 'hide') {
    $('#modals-delete_device').find('.delete-device').attr('onclick', "rid_delete('"+key+"')");
    $('#modals-delete_device').showMenu();
    return false;
  }
  $('#' + key).fadeOut(300, function () {
    $(this).remove();
  });
  $.get(rid_request_file(), {f: 'edit_listbutton', act: 'del', id:key});
}
</script>
<?php } else if ($datadefp['send_button'] == '2') { ?>
<center><h1>You do not have access to use this</h1></center>
<?php } else { ?>
<center><h1>This Feature Disabled</h1></center>
<?php } ?>