<!-- Homepage Slider-->
        <div class="content mt-0">
            <div class="row">
                <div class="col-6">
                    <a href="<?php echo $rid['site_url'];?>/index.php?link1=login" class="btn btn-full btn-m rounded-s text-uppercase font-900 shadow-xl bg-highlight">Login</a>
                </div>
                <div class="col-6">
                    <a href="<?php echo $rid['site_url'];?>/index.php?link1=register" class="btn btn-full btn-border btn-m rounded-s text-uppercase font-900 shadow-l border-highlight color-highlight">Create account</a>
                </div>
            </div>
        </div>

        
        <div class="content mb-2">
            <h5 class="float-left font-16 font-500">Features</h5>
            <div class="clearfix"></div>
        </div>

        <div class="double-slider text-center owl-carousel owl-no-dots">
            <div class="item bg-theme rounded-m shadow-m">
                <i class="mt-4 mb-4" data-feather="smartphone" data-feather-line="1" data-feather-size="45" data-feather-color="blue2-dark" data-feather-bg="blue2-fade-light"></i>
                <h5 class="font-16">Multi Device & Number</h5>
                <p class="line-height-s font-11">
                    You can add multiple whatsapp numbers with 1 account
                </p>
            </div>
            <div class="item bg-theme rounded-m shadow-m">
                <i class="mt-4 mb-4" data-feather="smartphone" data-feather-line="1" data-feather-size="45" data-feather-color="brown1-dark" data-feather-bg="brown1-fade-light"></i>
                <h5 class="font-16">Webhook</h5>
                <p class="line-height-s font-11">
                    Get callback data from our server
                </p>
            </div>
            <div class="item bg-theme rounded-m shadow-m">
                <i class="mt-4 mb-4" data-feather="smartphone" data-feather-line="1" data-feather-size="45" data-feather-color="yellow1-dark"  data-feather-bg="yellow1-fade-light"></i>
                <h5 class="font-16">Simple Rest API</h5>
                <p class="line-height-s font-11">
                    Simple API request
                </p>
            </div>
            <div class="item bg-theme rounded-m shadow-m">
                <i class="mt-4 mb-4" data-feather="smile" data-feather-line="1" data-feather-size="45" data-feather-color="green1-dark" data-feather-bg="green1-fade-light"></i>
                <h5 class="font-16">WhatsApp Blast</h5>
                <p class="line-height-s font-11">
                    Send bulk with schedule
                </p>
            </div>
            <div class="item bg-theme rounded-m shadow-m">
                <i class="mt-4 mb-4" data-feather="smile" data-feather-line="1" data-feather-size="45" data-feather-color="green1-dark" data-feather-bg="green1-fade-light"></i>
                <h5 class="font-16">Button message</h5>
                <p class="line-height-s font-11">
                    Send button message
                </p>
            </div>
            <div class="item bg-theme rounded-m shadow-m">
                <i class="mt-4 mb-4" data-feather="smile" data-feather-line="1" data-feather-size="45" data-feather-color="green1-dark" data-feather-bg="green1-fade-light"></i>
                <h5 class="font-16">And much more</h5>
                <p class="line-height-s font-11">
                    Login/register now, and you will see all the features in it
                </p>
            </div>
        </div>
        <div class="divider divider-margins"></div>
        <div class="card card-style mb-3 bg-10" data-card-height="110">
            <div class="card-center pl-3">
                <h1 class="color-white mb-n1 font-25">Package one</h1>
                <p class="opacity-50 color-white mb-0">- 1 device</p>
                <p class="opacity-50 color-white mb-0">- Have access to all features</p>
            </div>
            <div class="card-center pr-3">
                <p class="text-right opacity-50 color-white mb-0">RP, 25.000/monthly</p>
                <p class="text-right opacity-50 color-white mb-0">$1.60/monthly</p>
            </div>
            <div class="card-overlay bg-black opacity-90"></div>
        </div>

        <div class="card card-style mb-3" data-card-height="110">
            <div class="card-center pl-3">
                <h1 class="color-white mb-n1 font-25">Package two</h1>
                <p class="opacity-50 color-white mb-0">- 2 device</p>
                <p class="opacity-50 color-white mb-0">- Have access to all features</p>
            </div>
            <div class="card-center pr-3">
                <p class="text-right opacity-50 color-white mb-0">RP, 50.000/monthly</p>
                <p class="text-right opacity-50 color-white mb-0">$3.21/monthly</p>
            </div>
            <div class="card-overlay bg-gradient-red2 opacity-90"></div>
        </div>

        <div class="card card-style" data-card-height="110">
            <div class="card-center pl-3">
                <h1 class="color-white mb-n1 font-25">Package three</h1>
                <p class="opacity-50 color-white mb-0">- 5 device</p>
                <p class="opacity-50 color-white mb-0">- Have access to all features</p>
            </div>
            <div class="card-center pr-3">
                <p class="text-right opacity-50 color-white mb-0">RP, 100.000/monthly</p>
                <p class="text-right opacity-50 color-white mb-0">$6.41/monthly</p>
            </div>
            <div class="card-overlay bg-gradient-blue2 opacity-90"></div>
        </div>

        <div class="card card-style">
            <div class="content mb-2">
                <h3>Frequent Questions</h3>
                <p class="color-highlight font-12 mt-n2 mb-2">Really, we get asked this often.</p>
                <p>
                    We get asked these questions a lot, so we made this small section to help you out identifying what you need faster.
                </p>

                <div class="divider mt-2 mb-2"></div>

                <div class="d-flex">
                    <div class="pt-1">
                        <h5 data-activate="question-1" class="font-600">What is the number from the <?php echo $rid['web_setting']['title'];?>?</h5>
                    </div>
                    <div class="ml-auto mr-1 pr-2">
                        <div class="custom-control classic-switch">
                            <input type="checkbox" class="classic-input" id="question-1">
                            <label class="custom-control-label" for="question-1"></label>
                            <i class="fa fa-angle-down font-11 color-green1-dark"></i>
                        </div>
                    </div>
                </div>
                <div data-switch="question-1" class="switch-is-unchecked">
                    <p class="pb-3">
                        No, each user uses their own WhatsApp number, we only provide the service.
                    </p>
                </div>

                <div class="divider mt-2 mb-2"></div>

                <div class="d-flex">
                    <div class="pt-1">
                        <h5 data-activate="question-2" class="font-600">Is there an API and Webhooks?</h5>
                    </div>
                    <div class="ml-auto mr-1 pr-2">
                        <div class="custom-control classic-switch">
                            <input type="checkbox" class="classic-input" id="question-2">
                            <label class="custom-control-label" for="question-2"></label>
                            <i class="fa fa-angle-down font-11 color-green1-dark"></i>
                        </div>
                    </div>
                </div>
                <div data-switch="question-2" class="switch-is-unchecked">
                    <p class="pb-3">
                        <?php echo $rid['web_setting']['title'];?> provides a Rest API as well as a webhook for the needs of dynamic bots or some sort of website notification.
                    </p>
                </div>

                <div class="divider mt-2 mb-2"></div>

                <div class="d-flex">
                    <div class="pt-1">
                        <h5 data-activate="question-3" class="font-600">Can send a button message?</h5>
                    </div>
                    <div class="ml-auto mr-1 pr-2">
                        <div class="custom-control classic-switch">
                            <input type="checkbox" class="classic-input" id="question-3">
                            <label class="custom-control-label" for="question-3"></label>
                            <i class="fa fa-angle-down font-11 color-green1-dark"></i>
                        </div>
                    </div>
                </div>
                <div data-switch="question-3" class="switch-is-unchecked">
                    <p class="pb-3">
                        Yes, <?php echo $rid['web_setting']['title'];?> already supports sending button messages, be it list buttons, url buttons, or call buttons.
                    </p>
                </div>      

                <div class="divider mt-2 mb-2"></div>

                <div class="d-flex">
                    <div class="pt-1">
                        <h5 data-activate="question-4" class="font-600">Is whatsapp gateway official?</h5>
                    </div>
                    <div class="ml-auto mr-1 pr-2">
                        <div class="custom-control classic-switch">
                            <input type="checkbox" class="classic-input" id="question-4">
                            <label class="custom-control-label" for="question-4"></label>
                            <i class="fa fa-angle-down font-11 color-green1-dark"></i>
                        </div>
                    </div>
                </div>
                <div data-switch="question-4" class="switch-is-unchecked">
                    <p>
                        <?php echo $rid['web_setting']['title'];?> is not an official whatsapp provider, we are Unofficial Whatsapp Gateway.
                    </p>
                </div>

                <div class="divider mt-2 mb-2"></div>

                <div class="d-flex">
                    <div class="pt-1">
                        <h5 data-activate="question-5" class="font-600">Is there a guarantee that WhatsApp numbers will not be banned?</h5>
                    </div>
                    <div class="ml-auto mr-1 pr-2">
                        <div class="custom-control classic-switch">
                            <input type="checkbox" class="classic-input" id="question-5">
                            <label class="custom-control-label" for="question-5"></label>
                            <i class="fa fa-angle-down font-11 color-green1-dark"></i>
                        </div>
                    </div>
                </div>
                <div data-switch="question-5" class="switch-is-unchecked">
                    <p class="pb-3">
                        <?php echo $rid['web_setting']['title'];?> does not guarantee that your number is safe from being banned, please use it wisely.
                    </p>
                </div>
            </div>
        </div>