<div class="card card-style text-center">
            <div class="content pt-4 pb-4">
                <h1><i class="fa fa-exclamation-triangle color-red2-dark fa-5x"></i></h1>
                <h1 class="fa-6x pt-5 pb-2">404</h1>
                <h3 class="text-uppercase pb-3">Page not found!</h3>
                <p class="boxed-text-l">
                    The page you are looking for was not found.
                </p>
            </div>
        </div>