<div class="single-slider-boxed text-center owl-no-dots owl-carousel">
            <div class="card rounded-l shadow-l" data-card-height="320">
                <div class="card-bottom">
                    <h1 class="font-24 font-700"><?php echo $rid['web_setting']['title'];?></h1>
                    <p class="boxed-text-xl">
                        Bikin websitemu Jadi Keren Dengan <?php echo $rid['web_setting']['title'];?>
                    </p>
                </div>
                <div class="card-overlay bg-gradient-fade"></div>
                <div class="card-bg owl-lazy" data-src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/images/pictures/17m.jpg"></div>
            </div>
            <div class="card rounded-l shadow-l" data-card-height="320">
                <div class="card-bottom">
                    <h1 class="font-24 font-700"><?php echo $rid['web_setting']['title'];?></h1>
                    <p class="boxed-text-xl">
                        WhatsApp Gateway termurah dan tercepat di Indonesia
                    </p>
                </div>
                <div class="card-overlay bg-gradient-fade"></div>
                <div class="card-bg owl-lazy" data-src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/images/pictures/8m.jpg"></div>
            </div>
            <div class="card rounded-l shadow-l" data-card-height="320">
                <div class="card-bottom">
                    <h1 class="font-24 font-700"><?php echo $rid['web_setting']['title'];?></h1>
                    <p class="boxed-text-xl">
                        PILIH SESUAI KEBUTUHAN
                    </p>
                </div>
                <div class="card-overlay bg-gradient-fade"></div>
                <div class="card-bg owl-lazy" data-src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/images/pictures/14m.jpg"></div>
            </div>
        </div>