<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="<?php echo $rid['web_setting']['description'];?>">
    <meta name="author" content="RIDPEDIA">
    <meta name="keywords" content="<?php echo $rid['keywords'];?>">

    <title><?php echo $rid['title'];?></title>

    <!-- Custom fonts for this template-->
    <link href="<?php echo $rid['template_url'];?>/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="<?php echo $rid['template_url'];?>/assets/css/sb-admin-2.min.css" rel="stylesheet">
     <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>
      <script>
          function rid_request_file() {
              return "<?php echo $rid['site_url'];?>/req.php";
          }
          function base_url() {
              return "<?php echo $rid['site_url'];?>";
          }
          function rid_restart() {
            return "<?php echo $rid['site_url'];?>/request/restartall.php";
        }
      </script>

</head>

<body <?php if ($rid['loggedin'] == true) { echo 'id="page-top"'; } else { echo 'class="bg-gradient-primary"'; } ?>>

    <!-- Page Wrapper -->

        <?php if ($rid['loggedin'] == true) { ?>
        <div id="wrapper">
        <?php echo rid_LoadPage('sidebar/main'); ?>

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <?php echo rid_loadPage('header/main');?>

                <?php echo $rid['content'];?>

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; <?php echo $rid['web_setting']['title'];?></span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="<?php echo $rid['site_url'];?>/index.php?link1=logout">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <?php } else { ?>
    <?php echo $rid['content'];?>
    <?php } ?>

    <!-- Bootstrap core JavaScript-->
    <script>
         function sleep(milliseconds) {
            return new Promise(resolve => setTimeout(resolve, milliseconds));
         }
    </script>
    <script src="<?php echo $rid['template_url'];?>/assets/vendor/jquery/jquery.min.js"></script>
    <script src="<?php echo $rid['template_url'];?>/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="<?php echo $rid['template_url'];?>/assets/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="<?php echo $rid['template_url'];?>/assets/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="<?php echo $rid['template_url'];?>/assets/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="<?php echo $rid['template_url'];?>/assets/js/demo/chart-area-demo.js"></script>
    <script src="<?php echo $rid['template_url'];?>/assets/js/demo/chart-pie-demo.js"></script>

</body>

</html>