<div id="modal-change_pass" class="menu menu-box-bottom menu-box-detached rounded-m" 
         data-menu-height="320" 
         data-menu-effect="menu-over">
        <div class="content mb-0">
            <h1 class="font-700 mb-0">Change password</h1>
            <p class="font-11  mt-n1 mb-0">
                Please write a new your password.
            </p>
            <form class="langsModalForm" id="change_password" method="POST">
                <div class="langsModalAlert"></div>
                <div class="input-style has-icon input-style-1 input-required">
                    <i class="input-icon fa fa-lock font-11"></i>
                    <span>Write a new password</span>
                    <em>(required)</em>
                    <input type="password" placeholder="Write a new password" name="newpassword" id="newpassword" required>
                </div>
                <div class="input-style has-icon input-style-1">
                    <i class="input-icon fa fa-lock font-11"></i>
                    <span>Confirm new password</span>
                    <em>(required)</em>
                    <input type="password" placeholder="Confirm new password" name="newpassword2" id="newpassword2" required>
                </div>   
            </form>
            <button type="submit" class="btn btn-full btn-m shadow-l rounded-s text-uppercase font-900 bg-green1-dark mt-4 " onclick="rid_changePass();">Change</button>
        </div>
    </div>