<div id="modal-change_c_wa" class="menu menu-box-bottom menu-box-detached rounded-m" 
         data-menu-height="320" 
         data-menu-effect="menu-over">
        <div class="content mb-0">
            <h1 class="font-700 mb-0">Change contact whatsapp number</h1>
            <p class="font-11  mt-n1 mb-0">
                Please write a new your whatsapp number.
            </p>
            <form action="" method="POST">
                <div class="langsModalAlert"></div>
                <div class="input-style has-icon input-style-1 input-required">
                    <i class="input-icon fa fa-phone font-11"></i>
                    <span>Whatsapp number</span>
                    <em>(required)</em>
                    <input type="number" placeholder="Write a new number" name="c_wa" id="c_wa" required value="<?php echo $rid['dataUser']['c_wa'];?>">
                </div>
                <button type="submit" class="btn btn-full btn-m shadow-l rounded-s text-uppercase font-900 bg-green1-dark mt-4" name="change_wa">Save</button>
            </form>
        </div>
    </div>