<div id="modals-delete_device" class="menu menu-box-bottom menu-box-detached rounded-m"
         data-menu-height="200" 
         data-menu-effect="menu-over">
        <h2 class="text-center font-700 mt-3 pt-1">Are you sure?</h2>
        <p class="boxed-text-l">
            You want to delete?
        </p>
        <div class="row mr-3 ml-3">
            <div class="col-6">
                <a href="#" class="delete-device close-menu btn btn-sm btn-full button-s shadow-l rounded-s text-uppercase font-900 bg-green1-dark">Delete</a>
            </div>
            <div class="col-6">
                <a href="#" class="close-menu btn btn-sm btn-full button-s shadow-l rounded-s text-uppercase font-900 bg-red1-dark">Cancel</a>
            </div>
        </div>
    </div>  