<?php 
$u = $_SESSION['rid_username'];
$con = $rid['sqlConnect'];
?>
<div class="modal fade" id="edit_listbuttons" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content ">
            <div class="modal-header">
                <h4 class="modal-title" id="langsModalLabel">Edit</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="edit_autoreply" method="POST">
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel"><?php echo rid_lang('number');?> ID</label>
                                <input type="number" style="resize: none;" name="id" id="id" class="form-control" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">keyword</label>
                                <input style="resize: none;" name="keyword_edit" id="keyword_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                              <label class="form-label">text small</label>
                                <textarea name="text_small_edit" id="text_small_edit" class="form-control" cols="30" rows="10" style="height: 100px;"></textarea>
                                <small class="admin-info">Write your message here.</small>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">footer</label>
                                <input style="resize: none;" name="footer_edit" id="footer_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title message</label>
                                <input style="resize: none;" name="title_message_edit" id="title_message_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">buttonText</label>
                                <input style="resize: none;" name="buttontext_edit" id="buttontext_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title section</label>
                                <input style="resize: none;" name="title_section_edit" id="title_section_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list 1</label>
                                <input style="resize: none;" name="title_list_1_edit" id="title_list_1_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list keyword 1</label>
                                <input style="resize: none;" name="title_list_keyword_1_edit" id="title_list_keyword_1_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list desc 1 </label>
                                <input style="resize: none;" name="title_list_desc_1_edit" id="title_list_desc_1_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list 2</label>
                                <input style="resize: none;" name="title_list_2_edit" id="title_list_2_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list keyword 2</label>
                                <input style="resize: none;" name="title_list_keyword_2_edit" id="title_list_keyword_2_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list desc 2</label>
                                <input style="resize: none;" name="title_list_desc_2_edit" id="title_list_desc_2_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list 3</label>
                                <input style="resize: none;" name="title_list_3_edit" id="title_list_3_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list keyword 3</label>
                                <input style="resize: none;" name="title_list_keyword_3_edit" id="title_list_keyword_3_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list desc 3</label>
                                <input style="resize: none;" name="title_list_desc_3_edit" id="title_list_desc_3_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel"><?php echo rid_lang('number');?></label>
                                <input style="resize: none;" name="number" id="number" class="form-control" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">Username</label>
                                <input style="resize: none;" name="username" id="username" class="form-control" readonly>
                            </div>
                        </div>
                        <div class="data"></div>
                        <div class="langsModalAlert"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary modal_close_btn" data-dismiss="modal"><?php echo rid_lang('close');?></button>
                <button type="button" class="btn btn-primary" onclick="rid_edit();"><?php echo rid_lang('save');?></button>
            </div>
        </div>
    </div>
</div>