<?php 
$u = $_SESSION['rid_username'];
$con = $rid['sqlConnect'];
?>
<div class="modal fade" id="edit_autoreplyh" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content ">
            <div class="modal-header">
                <h4 class="modal-title" id="langsModalLabel">Edit</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="" id="edit_autoreply" method="POST" enctype="multipart/form-data">
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel"><?php echo rid_lang('number');?> Sender</label>
                                <input style="resize: none;" name="id" id="id" class="form-control" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">keyword</label>
                                <input style="resize: none;" name="keyword_edit" id="keyword_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">Image</label>
                                <input type="text" id="media_edit" name="media_edit" class="form-control">
                            </div>
                            <small class="admin-info">jpg/png</small>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                              <label class="form-label">Content</label>
                                <textarea name="content_edit" id="content_edit" class="form-control" cols="30" rows="10" style="height: 100px;"></textarea>
                                <small class="admin-info">Write your message here.</small>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">Footer</label>
                                <input style="resize: none;" name="foote_editr" id="footer_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">External link</label>
                                <input style="resize: none;" name="external_link_edit" id="external_link_edit" class="form-control" placeholder="ex: https://xxx">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">External link Button name</label>
                                <input style="resize: none;" name="external_link_name_edit" id="external_link_name_edit" class="form-control" placeholder="Visit my website">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">External telp</label>
                                <input style="resize: none;" name="external_telp_edit" id="external_telp_edit" class="form-control" placeholder="ex: 62815xxxx">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">External telp Button name</label>
                                <input style="resize: none;" name="external_telp_name_edit" id="external_telp_name_edit" class="form-control" placeholder="ex: Call me!">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">Keyword auto reply</label>
                                <input style="resize: none;" name="keyword_auto_reply_edit" id="keyword_auto_reply_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">Text button for keyword auto reply</label>
                                <input style="resize: none;" name="text_button_edit" id="text_button_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">keyword auto reply 2</label>
                                <input style="resize: none;" name="keyword_auto_replytwo_edit" id="keyword_auto_replytwo_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">Text button for keyword auto reply 2</label>
                                <input style="resize: none;" name="text_button_two_edit" id="text_button_two_edit" class="form-control">
                            </div>
                        </div>
                        <div class="data"></div>
                        <div class="langsModalAlert"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary modal_close_btn" data-dismiss="modal"><?php echo rid_lang('close');?></button>
                <button type="button" class="btn btn-primary" onclick="rid_edit();"><?php echo rid_lang('save');?></button>
            </div>
        </div>
    </div>
</div>