<?php 
$con = $rid['sqlConnect'];
$u = $_SESSION['rid_username'];
$datadefp = $rid['dataUser'];
if ($rid['web_setting']['autoreply_button'] == '1' && $datadefp['send_button'] == '1') { ?>
<div class="container-fluid">
    <div>
        <h3><?php echo rid_lang('auto_reply');?> List button</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page"><?php echo rid_lang('auto_reply');?> list button</li>
            </ol>
        </nav>
    </div>
    <!-- Widgets -->
    <div class="row clearfix">
    <div class="card">
        <div class="card-body">
			<button class="btn btn-info float-right" onclick="rid_AddAutoReply();"><?php echo rid_lang('add_auto_reply');?></button>
            <h6 class="card-title"><?php echo rid_lang('auto_reply');?> list button</h6>
            <div class="row">
                <div class="col-md-12" style="margin-bottom:0;">
                    <div class=" add_category_form_alert"></div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <br>
            <div class="table-responsive">
                <table id="example" class="table key-buttons text-md-nowrap">
                    <thead>
                        <tr>
                           <th>KEYWORD</th>
                           <th>TEXT SMALL</th>
                           <th>FOOTER</th>
                           <th>TITLE MESSAGE</th>
                           <th>BUTTON TEXT</th>
                           <th>TITLE SECTION</th>
                           <th>TITLE LIST 1</th>
                           <th>TITLE LIST KEYWORD 1</th>
                           <th>TITLE LIST DESC 1</th>
                           <th>TITLE LIST 2</th>
                           <th>TITLE LIST KEYWORD 2</th>
                           <th>TITLE LIST DESC 2</th>
                           <th>TITLE LIST 3</th>
                           <th>TITLE LIST KEYWORD 3</th>
                           <th>TITLE LIST DESC 3</th>
                           <th><?php echo rid_lang('number');?></th>
                           <th>USERNAME</th>
                           <th>action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $u = $_SESSION['rid_username'];
                        $q = mysqli_query($con, "SELECT * FROM list_button WHERE username = '$u'");
                        while ($row = mysqli_fetch_assoc($q)) { ?>
                        <tr id="<?= $row['id'];?>" data-selected="<?= $row['id'];?>">
                            <td><?= $row['keyword']; ?></td>
                            <td><?= $row['text_small']; ?></td>
                            <td><?= $row['footer']; ?></td>
                            <td><?= $row['title_message']; ?></td>
                            <td><?= $row['buttontext']; ?></td>
                            <td><?= $row['title_section']; ?></td>
                            <td><?= $row['title_list_1']; ?></td>
                            <td><?= $row['title_list_keyword_1']; ?></td>
                            <td><?= $row['title_list_desc_1']; ?></td>
                            <td><?= $row['title_list_2']; ?></td>
                            <td><?= $row['title_list_keyword_2']; ?></td>
                            <td><?= $row['title_list_desc_2']; ?></td>
                            <td><?= $row['title_list_3']; ?></td>
                            <td><?= $row['title_list_keyword_3']; ?></td>
                            <td><?= $row['title_list_desc_3']; ?></td>
                            <td><?= $row['number'];?></td>
                            <td><?= $row['username'];?></td>
                            <td>
                                <button onclick="rid_edits(`<?= $row["id"];?>`,`<?= $row["keyword"]; ?>`,`<?= $row["text_small"]; ?>`,`<?= $row["footer"]; ?>`,`<?= $row["title_message"]; ?>`,`<?= $row["buttontext"]; ?>`,`<?= $row["title_section"]; ?>`,`<?= $row["title_list_1"]; ?>`,`<?= $row["title_list_keyword_1"]; ?>`,`<?= $row["title_list_desc_1"]; ?>`,`<?= $row["title_list_2"]; ?>`,`<?= $row["title_list_keyword_2"]; ?>`,`<?= $row["title_list_desc_2"]; ?>`,`<?= $row["title_list_3"]; ?>`,`<?= $row["title_list_keyword_3"]; ?>`,`<?= $row["title_list_desc_3"]; ?>`,`<?= $row["number"]; ?>`,`<?= $row["username"]; ?>`);" type="button" class="btn bg-danger admn_table_btn">Edit</button>
                                <button onclick="rid_delete('<?= $row["id"];?>','hide');" type="button" class="btn bg-danger admn_table_btn"><?php echo rid_lang('delete');?></button>
                            </td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    </div>
    <!-- #END# Widgets -->
</div>

<div class="modal fade" id="edit_listbuttons" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content ">
            <div class="modal-header">
                <h4 class="modal-title" id="langsModalLabel">Edit</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="edit_autoreply" method="POST">
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel"><?php echo rid_lang('number');?> ID</label>
                                <input type="number" style="resize: none;" name="id" id="id" class="form-control" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">keyword</label>
                                <input style="resize: none;" name="keyword_edit" id="keyword_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                              <label class="form-label">text small</label>
                                <textarea name="text_small_edit" id="text_small_edit" class="form-control" cols="30" rows="10" style="height: 100px;"></textarea>
                                <small class="admin-info">Write your message here.</small>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">footer</label>
                                <input style="resize: none;" name="footer_edit" id="footer_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title message</label>
                                <input style="resize: none;" name="title_message_edit" id="title_message_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">buttonText</label>
                                <input style="resize: none;" name="buttontext_edit" id="buttontext_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title section</label>
                                <input style="resize: none;" name="title_section_edit" id="title_section_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list 1</label>
                                <input style="resize: none;" name="title_list_1_edit" id="title_list_1_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list keyword 1</label>
                                <input style="resize: none;" name="title_list_keyword_1_edit" id="title_list_keyword_1_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list desc 1 </label>
                                <input style="resize: none;" name="title_list_desc_1_edit" id="title_list_desc_1_edit" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list 2</label>
                                <input style="resize: none;" name="title_list_2_edit" id="title_list_2_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list keyword 2</label>
                                <input style="resize: none;" name="title_list_keyword_2_edit" id="title_list_keyword_2_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list desc 2</label>
                                <input style="resize: none;" name="title_list_desc_2_edit" id="title_list_desc_2_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list 3</label>
                                <input style="resize: none;" name="title_list_3_edit" id="title_list_3_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list keyword 3</label>
                                <input style="resize: none;" name="title_list_keyword_3_edit" id="title_list_keyword_3_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list desc 3</label>
                                <input style="resize: none;" name="title_list_desc_3_edit" id="title_list_desc_3_edit" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel"><?php echo rid_lang('number');?></label>
                                <input style="resize: none;" name="number" id="number" class="form-control" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">Username</label>
                                <input style="resize: none;" name="username" id="username" class="form-control" readonly>
                            </div>
                        </div>
                        <div class="data"></div>
                        <div class="langsModalAlert"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary modal_close_btn" data-dismiss="modal"><?php echo rid_lang('close');?></button>
                <button type="button" class="btn btn-primary" onclick="rid_edit();"><?php echo rid_lang('save');?></button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModal1Label"><?php echo rid_lang('delete');?> Auto reply</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <?php echo rid_lang('sure');?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php echo rid_lang('close');?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal"><?php echo rid_lang('delete');?></button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="add_autoreplyh" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content ">
            <div class="modal-header">
                <h4 class="modal-title" id="langsModalLabel"><?php echo rid_lang('add_numb');?></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="add_autoreply" method="POST">
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel"><?php echo rid_lang('number');?> Sender</label>
                        <select class="form-control show-tick" id="sender" name="sender">
                        <?php
                        $u = $_SESSION['rid_username'];
                        $q = mysqli_query($con, "SELECT * FROM device WHERE pemilik='$u' AND state = 'CONNECTED'");
                        while ($row = mysqli_fetch_assoc($q)) {
                            echo '<option value="' . $row['nomor'] . '">' . $row['nomor'] . ' (active)</option>';
                        }
                        ?>
                        </select>
                        <small class="admin-info">Choose sender.</small>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">keyword</label>
                                <input style="resize: none;" name="keyword" id="keyword" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                              <label class="form-label">text small</label>
                                <textarea name="text_small" id="text_small" class="form-control" cols="30" rows="10" style="height: 100px;"></textarea>
                                <small class="admin-info">Write your message here.</small>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">footer</label>
                                <input style="resize: none;" name="footer" id="footer" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title message</label>
                                <input style="resize: none;" name="title_message" id="title_message" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">buttontext</label>
                                <input style="resize: none;" name="buttontext" id="buttontext" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title section</label>
                                <input style="resize: none;" name="title_section" id="title_section" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list 1</label>
                                <input style="resize: none;" name="title_list_1" id="title_list_1" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list keyword 1</label>
                                <input style="resize: none;" name="title_list_keyword_1" id="title_list_keyword_1" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list desc 1</label>
                                <input style="resize: none;" name="title_list_desc_1" id="title_list_desc_1" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list 2</label>
                                <input style="resize: none;" name="title_list_2" id="title_list_2" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list keyword 2</label>
                                <input style="resize: none;" name="title_list_keyword_2" id="title_list_keyword_2" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list desc 2</label>
                                <input style="resize: none;" name="title_list_desc_2" id="title_list_desc_2" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list 3</label>
                                <input style="resize: none;" name="title_list_3" id="title_list_3" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list keyword 3</label>
                                <input style="resize: none;" name="title_list_keyword_3" id="title_list_keyword_3" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel">title list desc 3</label>
                                <input style="resize: none;" name="title_list_desc_3" id="title_list_desc_3" class="form-control">
                            </div>
                        </div>
                        <div class="data"></div>
                        <div class="langsModalAlert"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary modal_close_btn" data-dismiss="modal"><?php echo rid_lang('close');?></button>
                <button type="button" class="btn btn-primary" onclick="rid_add();"><?php echo rid_lang('save');?></button>
            </div>
        </div>
    </div>
</div>

<script>

const sleep = (milliseconds) => {
  return new Promise(resolve => setTimeout(resolve, milliseconds))
}

function rid_edit() {
    $('#edit_autoreply').submit();
}

function rid_add() {
    $('#add_autoreply').submit();
}

$(document).ready(function () {
  $("#edit_autoreply").submit(function (event) {
      const id = document.getElementById("id");
      const keyword = document.getElementById("keyword_edit");
      const text_small = document.getElementById("text_small_edit");
      const footer = document.getElementById("footer_edit");
      const title_message = document.getElementById("title_message_edit");
      const buttontext = document.getElementById("buttontext_edit");
      const title_section = document.getElementById("title_section_edit");
      const title_list_1 = document.getElementById("title_list_1_edit");
      const title_list_keyword_1 = document.getElementById("title_list_keyword_1_edit");
      const title_list_desc_1 = document.getElementById("title_list_desc_1_edit");
      const title_list_2 = document.getElementById("title_list_2_edit");
      const title_list_keyword_2 = document.getElementById("title_list_keyword_2_edit");
      const title_list_desc_2 = document.getElementById("title_list_desc_2_edit");
      const title_list_3 = document.getElementById("title_list_3_edit");
      const title_list_keyword_3 = document.getElementById("title_list_keyword_3_edit");
      const title_list_desc_3 = document.getElementById("title_list_desc_3_edit");
      
      const edit = {
          id: id.value,
          keyword: keyword.value,
          text_small: text_small.value,
          footer: footer.value,
          title_message: title_message.value,
          buttontext: buttontext.value,
          title_section: title_section.value,
          title_list_1: title_list_1.value,
          title_list_keyword_1: title_list_keyword_1.value,
          title_list_desc_1: title_list_desc_1.value,
          title_list_2: title_list_2.value,
          title_list_keyword_2: title_list_keyword_2.value,
          title_list_desc_2: title_list_desc_2.value,
          title_list_3: title_list_3.value,
          title_list_keyword_3: title_list_keyword_3.value,
          title_list_desc_3: title_list_desc_3.value
      };
      
      $.ajax({
          url: rid_request_file() + '?f=edit_listbutton',
          beforeSend: function() {
              $('.langsModalAlert').html('<div class="alert alert-info">Waiting...</div>')
          },
          type: "POST",
          data: edit,
      }).done(async (data) => {
          console.log(data);
          var ridCans = JSON.parse(data);
          if (ridCans.status == 200) {
              await sleep(2000);
              $('#langsModal').modal('hide');
              location.reload();
          } else {
              console.log('this error ' + data);
              $('.langsModalAlert').html('<div class="alert alert-danger">'+ridCans.message+'</div>');
              setTimeout(function () {
                  $('.langsModalAlert').empty();
              }, 5000);
          }
          $("#langsModal").animate({ scrollTop: 0 }, 100);
      });
    event.preventDefault();
  });
});

    
$(document).ready(function () {
  $("#add_autoreply").submit(function (event) {
      const sender = document.getElementById("sender");
      const keyword = document.getElementById("keyword");
      const text_small = document.getElementById("text_small");
      const footer = document.getElementById("footer");
      const title_message = document.getElementById("title_message");
      const buttontext = document.getElementById("buttontext");
      const title_section = document.getElementById("title_section");
      const title_list_1 = document.getElementById("title_list_1");
      const title_list_keyword_1 = document.getElementById("title_list_keyword_1");
      const title_list_desc_1 = document.getElementById("title_list_desc_1");
      const title_list_2 = document.getElementById("title_list_2");
      const title_list_keyword_2 = document.getElementById("title_list_keyword_2");
      const title_list_desc_2 = document.getElementById("title_list_desc_2");
      const title_list_3 = document.getElementById("title_list_3");
      const title_list_keyword_3 = document.getElementById("title_list_keyword_3");
      const title_list_desc_3 = document.getElementById("title_list_desc_3");
      
      const addbutton = {
          sender: sender.value,
          keyword: keyword.value,
          text_small: text_small.value,
          footer: footer.value,
          title_message: title_message.value,
          buttontext: buttontext.value,
          title_section: title_section.value,
          title_list_1: title_list_1.value,
          title_list_keyword_1: title_list_keyword_1.value,
          title_list_desc_1: title_list_desc_1.value,
          title_list_2: title_list_2.value,
          title_list_keyword_2: title_list_keyword_2.value,
          title_list_desc_2: title_list_desc_2.value,
          title_list_3: title_list_3.value,
          title_list_keyword_3: title_list_keyword_3.value,
          title_list_desc_3: title_list_desc_3.value
      };
      
      $.ajax({
          url: rid_request_file() + '?f=add_listbutton',
          beforeSend: function() {
              $('.langsModalAlert').html('<div class="alert alert-info">Waiting...</div>')
          },
          type: "POST",
          data: addbutton,
      }).done(async (data) => {
          console.log(data);
          var ridCans = JSON.parse(data);
          if (ridCans.status == 200) {
              await sleep(2000);
              $('#langsModal').modal('hide');
              location.reload();
          } else {
              console.log('this error ' + data);
              $('.langsModalAlert').html('<div class="alert alert-danger">'+ridCans.message+'</div>');
              setTimeout(function () {
                  $('.langsModalAlert').empty();
              }, 5000);
          }
          $("#langsModal").animate({ scrollTop: 0 }, 100);
      });
    event.preventDefault();
  });
});

function rid_edits(id,keyword,text_small,footer,title_message,buttontext,title_section,title_list_1,title_list_keyword_1,title_list_desc_1,title_list_2,title_list_keyword_2,title_list_desc_2,title_list_3,title_list_keyword_3,title_list_desc_3,number,username) {
    $('#edit_listbuttons').modal('show');
    document.getElementById("id").setAttribute("value", id);
    document.getElementById("keyword_edit").setAttribute("value", keyword);
    document.getElementById("text_small_edit").value = text_small;
    document.getElementById("footer_edit").setAttribute("value", footer);
    document.getElementById("title_message_edit").setAttribute("value", title_message);
    document.getElementById("buttontext_edit").setAttribute("value", buttontext);
    document.getElementById("title_section_edit").setAttribute("value", title_section);
    document.getElementById("title_list_1_edit").setAttribute("value", title_list_1);
    document.getElementById("title_list_keyword_1_edit").setAttribute("value", title_list_keyword_1);
    document.getElementById("title_list_desc_1_edit").setAttribute("value", title_list_desc_1);
    document.getElementById("title_list_2_edit").setAttribute("value", title_list_2);
    document.getElementById("title_list_keyword_2_edit").setAttribute("value", title_list_keyword_2);
    document.getElementById("title_list_desc_2_edit").setAttribute("value", title_list_desc_2);
    document.getElementById("title_list_3_edit").setAttribute("value", title_list_3);
    document.getElementById("title_list_keyword_3_edit").setAttribute("value", title_list_keyword_3);
    document.getElementById("title_list_desc_3_edit").setAttribute("value", title_list_desc_3);
    document.getElementById("number").setAttribute("value", number);
    document.getElementById("username").setAttribute("value", username);
}

function rid_AddAutoReply() {
    $('#add_autoreplyh').modal('show');
}

function rid_delete(key,type = 'show') {
  if (key == '') {
    return false;
  }
  if (type == 'hide') {
    $('#DeleteModal').find('.btn-primary').attr('onclick', "rid_delete('"+key+"')");
    $('#DeleteModal').modal('show');
    return false;
  }
  $('#' + key).fadeOut(300, function () {
    $(this).remove();
  });
  $.get(rid_request_file(), {f: 'edit_listbutton', act: 'del', id:key});
}
</script>
<?php } else if ($datadefp['send_button'] == '2') { ?>
<center><h1>You do not have access to use this</h1></center>
<?php } else { ?>
<center><h1>This Feature Disabled</h1></center>
<?php } ?>