    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form class="user" method="POST" id="register">
                                         <div id="remsult" class="errors-rid"></div>
                                         <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                id="fullName" aria-describedby="fullName"
                                                placeholder="Full Name..." name="fullName" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="email" aria-describedby="email"
                                                placeholder="Email..." name="email" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                id="username" aria-describedby="username"
                                                placeholder="Username..." name="username" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" placeholder="Password" name="password" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="number" class="form-control form-control-user"
                                                id="number" placeholder="Whatsapp number" name="nowa" required>
                                        </div>
                                        <button type="submit" class="main-bt btn btn-primary btn-user btn-block" id="sign_submit">
                                            Register
                                        </button>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="<?php echo $rid['site_url'];?>/index.php?link1=login">Login!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
<script>
var $this = $('#register');
var $state = $this.find('.errors-rid');
$(function() {
  $this.ajaxForm({
    url: rid_request_file() + '?f=register',
    beforeSend: function() {
		$this.find('.main_bt').attr("disabled", true);
		$this.find('.main_bt').html('Please wait..');
    },
    success: function(data) {
      data = JSON.parse(data);
      if (data.status == true) {
        $state.html('<p style="color: green;">Welcome back!</p>');
		$this.find('.main_bt').html('Successfully');
        setTimeout(function () {
         window.location.href = window.location;
        }, 1000);
      } else {
        $this.find('.main_bt').attr("disabled", false);
		$this.find('.main_bt').html('Login');
        $state.html(`<p style="color: red;">${data.errors}</p>`);
      }
    }
  });
});
</script>